name: Main CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Testing Application
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [12.x, 14.x]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Fetch origin main
        run: git fetch origin main

      - name: Getting yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Installing Dependencies
        run: yarn install --prefer-offline

      - name: Running Lint
        run: yarn lint

      - name: Running Tests
        run: yarn test --silent

      # - uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      #     files: ../../coverage/clover.xml
      #     fail_ci_if_error: true

      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            threshold: 80

      - name: Building Application
        run: yarn build
